services:
  dashboard:
    build: ./apps/dashboard
    container_name: dashboard-dev
    ports:
      - "8500:8500"
    volumes:
      - ./apps/dashboard:/app
      - /app/node_modules

  login:
    build: ./apps/login
    container_name: login-dev
    ports:
      - "8501:8501"
    volumes:
      - ./apps/login:/app
      - /app/node_modules

  root-config:
    build: ./apps/root-config
    container_name: root-config-dev
    ports:
      - "9000:9000"
    volumes:
      - ./apps/root-config:/app
      - /app/node_modules

  api:
    build: ./apps/api
    container_name: api-dev
    ports:
      - "3000:3000"
    volumes:
      - ./apps/api:/app
      - /app/node_modules
    environment:
        - MONGO_URI=mongodb://admin:admin123@mongodb:27017/bytebank?authSource=admin
        - MONGO_DB_NAME=bytebank
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongo-dev
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
